name: Build App

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build manifest-editor
        run: |
          ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ManifestEditor
          path: lib
